name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    LND_TBL_M4RCH_ORGANIZATION_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4RCH_ORGANIZATION
    LND_TBL_M4RCH_ORGANIZATION_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4RCH_ORGANIZATION
    LND_TBL_M4RCH_ORGANIZATION_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4RCH_ORGANIZATION
    LND_TBL_M4RCH_ORGANIZATION_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4RCH_ORGANIZATION
    LND_TBL_M4RCH_ORGANIZATION: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4RCH_ORGANIZATION
    LND_TBL_M4CCL_POSITION_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_POSITION
    LND_TBL_M4CCL_POSITION_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_POSITION
    LND_TBL_M4CCL_POSITION_ab3: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_POSITION
    LND_TBL_M4CCL_POSITION: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_POSITION
    LND_TBL_STD_HR_PERIOD_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_HR_PERIOD
    LND_TBL_STD_HR_PERIOD_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_HR_PERIOD
    LND_TBL_STD_HR_PERIOD_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_HR_PERIOD
    LND_TBL_STD_HR_PERIOD_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_HR_PERIOD
    LND_TBL_STD_HR_PERIOD: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_HR_PERIOD
    LND_TBL_M4SCO_H_HR_LEGENT_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_LEGENT
    LND_TBL_M4SCO_H_HR_LEGENT_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_LEGENT
    LND_TBL_M4SCO_H_HR_LEGENT_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_LEGENT
    LND_TBL_M4SCO_H_HR_LEGENT_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_LEGENT
    LND_TBL_M4SCO_H_HR_LEGENT: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_LEGENT
    LND_TBL_M4SCO_H_HR_POS_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_POS
    LND_TBL_M4SCO_H_HR_POS_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_POS
    LND_TBL_M4SCO_H_HR_POS_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_POS
    LND_TBL_M4SCO_H_HR_POS_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_POS
    LND_TBL_M4SCO_H_HR_POS: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_H_HR_POS
    LND_TBL_M4CLI_REGIONES_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CLI_REGIONES
    LND_TBL_M4CLI_REGIONES_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CLI_REGIONES
    LND_TBL_M4CLI_REGIONES_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CLI_REGIONES
    LND_TBL_M4CLI_REGIONES_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CLI_REGIONES
    LND_TBL_M4CLI_REGIONES: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CLI_REGIONES
    LND_TBL_STD_LEG_ENT_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LEG_ENT
    LND_TBL_STD_LEG_ENT_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LEG_ENT
    LND_TBL_STD_LEG_ENT_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LEG_ENT
    LND_TBL_STD_LEG_ENT_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LEG_ENT
    LND_TBL_STD_LEG_ENT: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LEG_ENT
    LND_TBL_STD_LU_GENDER_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LU_GENDER
    LND_TBL_STD_LU_GENDER_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LU_GENDER
    LND_TBL_STD_LU_GENDER_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LU_GENDER
    LND_TBL_STD_LU_GENDER_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LU_GENDER
    LND_TBL_STD_LU_GENDER: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_LU_GENDER
    LND_TBL_M4CCL_HR_PERIOD_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_HR_PERIOD
    LND_TBL_M4CCL_HR_PERIOD_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_HR_PERIOD
    LND_TBL_M4CCL_HR_PERIOD_ab3: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_HR_PERIOD
    LND_TBL_M4CCL_HR_PERIOD: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4CCL_HR_PERIOD
    LND_TBL_STD_PERSON_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_PERSON
    LND_TBL_STD_PERSON_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_PERSON
    LND_TBL_STD_PERSON_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_PERSON
    LND_TBL_STD_PERSON_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_PERSON
    LND_TBL_STD_PERSON: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_STD_PERSON
    LND_TBL_M4SCO_HR_ROLE_ab1: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_HR_ROLE
    LND_TBL_M4SCO_HR_ROLE_ab2: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_HR_ROLE
    LND_TBL_M4SCO_HR_ROLE_stg: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_HR_ROLE
    LND_TBL_M4SCO_HR_ROLE_scd: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_HR_ROLE
    LND_TBL_M4SCO_HR_ROLE: lnd_ula_pnet_prd._airbyte_raw_LND_TBL_M4SCO_HR_ROLE
