version: 2
sources:
- name: lnd_ula_pnet_prd
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_LND_TBL_M4CCL_HR_PERIOD
  - name: _airbyte_raw_LND_TBL_M4CCL_POSITION
  - name: _airbyte_raw_LND_TBL_M4CLI_REGIONES
  - name: _airbyte_raw_LND_TBL_M4RCH_ORGANIZATION
  - name: _airbyte_raw_LND_TBL_M4SCO_HR_ROLE
  - name: _airbyte_raw_LND_TBL_M4SCO_H_HR_LEGENT
  - name: _airbyte_raw_LND_TBL_M4SCO_H_HR_POS
  - name: _airbyte_raw_LND_TBL_STD_HR_PERIOD
  - name: _airbyte_raw_LND_TBL_STD_LEG_ENT
  - name: _airbyte_raw_LND_TBL_STD_LU_GENDER
  - name: _airbyte_raw_LND_TBL_STD_PERSON
